### ISSUE TITLE
Should the IMG_DATE config variable be supported ?

### ISSUE THREAD

**Issue by NorthernMan54** [usimd/pi-gen-action#94]
With the IMG_DATE config variable set, the image name could be fixed so that it doesn't change with each build, making it easier for further steps to leverage the image.

ie

```
-rw-r--r--  1 runner docker  92K Nov 13 04:22 Raspbian-Homebridge-bookworm-64-bit.info
[5731](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6857431955/job/18646515236#step:3:5735)
  -rw-r--r--  1 runner docker 381K Nov 13 04:24 build-docker.log
[5732](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6857431955/job/18646515236#step:3:5736)
  -rw-r--r--  1 runner docker  15K Nov 13 04:24 build.log
[5733](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6857431955/job/18646515236#step:3:5737)
  -rw-r--r--  1 runner docker 874M Nov 13 04:24 image_Raspbian-Homebridge-bookworm-64-bit.zip
```

VS

-rw-r--r--  1 runner docker  92K Nov 12 23:56 2023-11-12-Homebridge-64bit.info
[6054](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6843772626/job/18606732032#step:4:6058)
  -rw-r--r--  1 runner docker 416K Nov 12 23:58 build-docker.log
[6055](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6843772626/job/18606732032#step:4:6059)
  -rw-r--r--  1 runner docker  15K Nov 12 23:58 build.log
[6056](https://github.com/NorthernMan54/homebridge-raspbian-image/actions/runs/6843772626/job/18606732032#step:4:6060)
  -rw-r--r--  1 runner docker 874M Nov 12 23:58 image_2023-11-12-Homebridge-64bit.zip

FYI - This was built by setting `docker-opts: '--env IMG_DATE=Raspbian'` as a kludge

**Comment by usimd** [comment]
I don't have a very strong opinion on this but did explicitly not include it as it seems common practice for GitHub actions to not be one-size-fits-all solutions.

The action does expose the final image name as output in `outputs.image-path` and it should be most secure for downstream steps to use this property instead of a custom naming schema.

Even if following an explicit file name pattern was a hard requirement, one could easily add a step doing a  `run: mv ${{ steps.<id>.outputs.image-path}} <your-file-name>` after the build.

Curious to learn though, how other workflows may look like and what specific constraints there might be.

**Comment by NorthernMan54** [comment]
Tks for the feedback, and as I'm just updating a build process that was originally setup by another team member, I went back and looked at what was happening and removed my workaround `docker-opts: '--env IMG_DATE=Raspbian'` and added this instead.

```
      - name: Get IMGFILENAME
        run: |
          export IMGFILENAME=`basename ${{ steps.build.outputs.image-path }}`
          echo "IMGFILENAME=${IMGFILENAME}" >> $GITHUB_ENV
```

Under the covers I'm creating a multi-image generation process, to create both 32-bit and 64-bit images, and make them available for RPI Imager.
